/temp/file1.c
/home/azur/Documents/python-logs/testing/testing_msg.sh
/var/file.ext
/usr/share/doc
/home/azur/projects
/var/log/myapp/debug.log
/home/azur/Documents/python-logs
/home/azur/directory_tree.conf
/home/azur/Documents/python-logs/testing/testing.sh