log_lines = [
    "Started app-gnome-org.wezfurlong.wezterm-7060.scope - Application launched by gnome-shell.",
    "warning: queue 0x5e3f193d0460 destroyed while proxies still attached:",
    "wl_subsurface#61 still attached",
    "wl_surface#60 still attached",
    "wl_subsurface#69 still attached",
    "wl_surface#68 still attached",
    "wl_subsurface#67 still attached",
    "wl_surface#66 still attached",
    "wl_subsurface#65 still attached",
    "wl_surface#64 still attached",
    "wl_subsurface#63 still attached",
    "wl_surface#62 still attached",
    "wl_callback#68 still attached",
    "xdg_wm_base#61 still attached",
    "wl_surface#60 still attached",
    "wl_data_device#17 still attached",
    "wl_pointer#65 still attached",
    "zwp_text_input_v3#14 still attached",
    "wl_keyboard#63 still attached",
    "zwp_primary_selection_device_v1#12 still attached",
    "zwp_primary_selection_device_manager_v1#3 still attached",
    "wl_data_device#61 still attached",
    "zwp_text_input_manager_v3#10 still attached",
    "wl_seat#9 still attached"
]
